defaults:
  - data: default_data

name: unittest
device: 
  _target_: torch.device
  device: "cuda:0"
arch:
  _target_: tts.model.PlaceholderModel
logger:
  _target_: tts.logger.logger.get_logger
  experiment_name: ${name}
  name: train
  save_dir: ${trainer.save_dir}
preprocessing:
  sr: 22050
text_encoder:
  _target_: tts.text_encoder.FastSpeechEncoder
  cleaners:
    - english_cleaners
  pad_token: <pad>
optimizer:
  _target_: torch.optim.Adam
  weight_decay: 1.0e-06
  lr: 1
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-09
loss:
  _target_: tts.loss.FastSpeech2Loss
  w_pitch: 1
  w_align: 1
  w_energy: 1
metrics: []
lr_scheduler:
  _target_: tts.scheduler.getTransformerScheduler
  warmup_steps: 4000
  d_model: 256
trainer:
  _target_: tts.trainer.Trainer
  epochs: 200
  save_dir: saved/${name}/
  save_period: 10
  verbosity: 2
  monitor: min val_loss
  early_stop: 1000
  visualize: wandb
  wandb_project: tts_project
  len_epoch: 210
  grad_norm_clip: 1
