defaults:
  - default

name: fastspeech1
n_gpu: 1
preprocessing:
  sr: 22050
arch:
  _target_: tts.model.FastSpeechModel
  vocab_size: 300
  max_seq_len: 3000
  encoder_dim: 256
  encoder_n_layer: 4
  encoder_head: 2
  encoder_conv1d_filter_size: 1024
  decoder_dim: 256
  decoder_n_layer: 4
  decoder_head: 2
  decoder_conv1d_filter_size: 1024
  fft_conv1d_kernel:
  - 9
  - 1
  fft_conv1d_padding:
  - 4
  - 0
  duration_predictor_filter_size: 256
  duration_predictor_kernel_size: 3
  dropout: 0.1
  PAD: 0
  num_mels: 80
loss:
  _target_: tts.loss.FastSpeechLoss