defaults:
  - fastspeech2

name: inference
data:
  test:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 2
    shuffle: False
    drop_last: False
    collate_fn: 
      _target_: tts.collate_fn.get_collate_fn
    dataset:
      _target_: tts.datasets.CustomTextDataset
      text_encoder: ${text_encoder}
      texts:
      - A defibrillator is a device that gives a high energy electric shock to the
        heart of someone who is in cardiac arrest
      - Massachusetts Institute of Technology may be best known for its math, science
        and engineering education
      - Wasserstein distance or Kantorovich Rubinstein metric is a distance function
        defined between probability distributions on a given metric space
      configurations:
      - duration: 1
        energy: 1
        pitch: 1
      - duration: 1
        energy: 2
        pitch: 1
      - duration: 1
        energy: 1
        pitch: 2
      - duration: 1.2
        energy: 1
        pitch: 1
      - duration: 0.8
        energy: 1
        pitch: 1
      - duration: 1
        energy: 1.2
        pitch: 1
      - duration: 1
        energy: 0.8
        pitch: 1
      - duration: 1
        energy: 1
        pitch: 1.2
      - duration: 1
        energy: 1
        pitch: 0.8
      - duration: 1.2
        energy: 1.2
        pitch: 1.2
      - duration: 0.8
        energy: 0.8
        pitch: 0.8
trainer:
  _target_: tts.trainer.Inferencer
  out_dir: synthesized_audios
  name: inference